name: Clash 配置转换

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # 每天 UTC 4 点自动运行，更新规则集
  - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      subscription_url:
        description: '订阅链接'
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 安装依赖
        run: |
          npm install -g yaml
          
      - name: 转换配置
        run: |
          # 创建输入目录
          mkdir -p input
          
          # 下载订阅链接
          if [ -n "${{ github.event.inputs.subscription_url }" ]; then
            echo "从订阅链接下载配置..."
            curl -L "${{ github.event.inputs.subscription_url }" -o input/config.yaml
          else
            echo "使用默认示例配置..."
            cat > input/config.yaml << 'EOF
          port: 7890
          socks-port: 7891
          mixed-port: 7892
          allow-lan: true
          mode: rule
          log-level: info
          external-controller: unix:///run/clash-controller.sock
          EOF
          fi
          
          # 运行转换脚本
          node converter.js input/config.yaml > output/config.yaml
          
      - name: 上传配置文件
        uses: actions/upload-artifact@v4
        with:
          name: clash-config
          path: output/
          
      - name: 创建发布页面
        run: |
          mkdir -p pages
          cat > pages/index.html << 'EOF
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Clash 配置转换器</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      line-height: 1.6;
      color: #333;
    }
    .container {
      background-color: #f5f5f5;
      border-radius: 8px;
      padding: 20px;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }
    h1 {
      color: #2c3e50;
      text-align: center;
      margin-bottom: 30px;
    }
    .form-group {
      margin-bottom: 20px;
    }
    label {
      display: block;
      margin-bottom: 5px;
      font-weight: bold;
    }
    textarea {
      width: 100%;
      height: 200px;
      padding: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-family: monospace;
      resize: vertical;
    }
    button {
      background-color: #4CAF50;
      color: white;
      border: none;
      padding: 10px 20px;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
      width: 100%;
    }
    button:hover {
      background-color: #45a049;
    }
    .result {
      margin-top: 20px;
      padding: 15px;
      background-color: #e9ecef;
      border-radius: 4px;
      white-space: pre-wrap;
      font-family: monospace;
      font-size: 12px;
      max-height: 400px;
      overflow-y: auto;
    }
    .info {
      margin-top: 20px;
      padding: 15px;
      background-color: #d1ecf1;
      border-radius: 4px;
      font-size: 14px;
    }
    .download-btn {
      display: inline-block;
      margin-right: 10px;
      margin-top: 10px;
      background-color: #007bff;
    }
    .download-btn:hover {
      background-color: #0056b3;
    }
    .github-btn {
      background-color: #24292e;
    }
    .github-btn:hover {
      background-color: #1a1a1a;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Clash 配置转换器</h1>
    
    <div class="form-group">
      <label for="subscription">订阅链接:</label>
      <textarea id="subscription" placeholder="请输入 Clash 订阅链接" rows="3"></textarea>
    </div>
    
    <button onclick="convertConfig()">转换配置</button>
    
    <div class="result" id="result" style="display: none;">
      <h3>转换后的配置:</h3>
      <pre id="result-text"></pre>
    </div>
    
    <div class="info">
      <h3>使用说明:</h3>
      <ol>
        <li>输入 Clash 订阅链接或直接粘贴配置内容</li>
        <li>点击"转换配置"按钮进行转换</li>
        <li>转换后的配置可以直接下载使用</li>
      </ol>
    </div>
    
    <div style="text-align: center; margin-top: 20px;">
      <button class="download-btn" onclick="downloadConfig()">下载配置文件</button>
      <button class="github-btn" onclick="window.open('https://github.com/yourusername/clash-config-converter')">
        <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor" style="vertical-align: middle; margin-right: 5px;">
          <path d="M8 0C3.58 0 0 3.58 0 1.24 1.46l-4.17 4.17c-.96.96-2.12 2.12-2.12 2.12 0 2.83.22 3.5.96.42.04 1.64.04 1.64 0 2.83-.22 3.5-.96 1.46-4.17 4.17zM8 2.83c0-1.1.9-2 2-2 2-.3 0-.5.5-1.1.9-1.6 1.4-.3.3-.6.6-.7 1.2-.1.8.1.8.1.8 0 3.42-1.64 1.64-1.64 0-2.83-.22-3.5-.96-.42-.04-1.64-.04-1.64 0-2.83.22-3.5.96 1.46-4.17 4.17zM12.16 8.16c-1.1.9-2 2-2 2-.3 0-.5.5-1.1.9-1.6 1.4-.3.3-.6.6-.7 1.2-.1.8.1.8.1.8 0 3.42-1.64 1.64-1.64 0-2.83-.22-3.5-.96-.42-.04-1.64-.04-1.64 0-2.83.22-3.5.96 1.46-4.17 4.17z"/>
        </svg>
        GitHub 仓库
      </button>
    </div>
  </div>

  <script>
    // 这里是您的脚本内容
    // ...
    
    function convertConfig() {
      const subscription = document.getElementById('subscription').value.trim();
      const resultDiv = document.getElementById('result');
      const resultText = document.getElementById('result-text');
      
      if (!subscription) {
        alert('请输入订阅链接');
        return;
      }
      
      resultDiv.style.display = 'block';
      resultText.textContent = '正在转换配置，请稍候...';
      
      fetch(subscription)
        .then(response => response.text())
        .then(configText => {
          try {
            const config = YAML.parse(configText);
            const result = main(config);
            resultText.textContent = YAML.stringify(result, null, 2);
          } catch (error) {
            resultText.textContent = "错误: " + error.message;
          }
        })
        .catch(error => {
          resultText.textContent = "下载失败: " + error.message;
        });
    }
    
    function downloadConfig() {
      const resultText = document.getElementById('result-text').textContent;
      if (!resultText || resultText.includes("错误:")) {
        alert('请先转换配置');
        return;
      }
      
      const blob = new Blob([resultText], { type: 'text/yaml' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'clash-config.yaml';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
  </script>
</body>
</html>
EOF
          
      - name: 上传页面
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: pages/
          
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: ./pages
EOF
